from pymongo import MongoClient
import pandas as pd
import numpy as np
import dns


### Connect to Atlas Cluster
client = MongoClient('mongodb://rjnagley:schnitzel1@cluster0-shard-00-00-3llbe.mongodb.net:27017,cluster0-shard-00-01-3llbe.mongodb.net:27017,cluster0-shard-00-02-3llbe.mongodb.net:27017/cluster0?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority')
db = client.test

### Load Data Generated by recipe_tagger.py


recipes = pd.read_csv("recipes_updated2.csv")

#convert keywords to list
def make_list(x):
    new = str(x).split(",")
    new = [y.strip(' ') for y in new]
    return new

recipes['keywords'] =  recipes['keywords'].apply(lambda x: make_list(x))


### Create Collection Called 'Recipes' from recipes CSV
url = list(recipes['link'])
meal = list(recipes['meal'])
tags = list(recipes['keywords'])
cooktime = list(recipes['time'])
servings = list(recipes['yield'])

for x in range(0, len(recipes)):
    recipe = {
        'url' : url[x],
        'meal' : meal[x],
        'tags' : tags[x],
        'cooktime': cooktime[x],
    }
    result=db.recipes.insert_one(recipe)


### Create collection called "ingredient_tags" from tagged_ingredients csv
tagged_ingredients = pd.read_csv(r"tagged_ingredients.csv")


ingredient = list(tagged_ingredients['Name'])
tag = list(tagged_ingredients['Category'])


for x in range(0, len(tagged_ingredients)):
    ingredient_tag = {
        'ingredient' : ingredient[x],
        'tag' : tag[x],
    }
    result=db.ingredient_tags.insert_one(ingredient_tag)
